banksite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('banksite_app.urls')),
    path('credentials/',include('credentials.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

banksite_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home, name='Home'),
    path('add/', views.person_create_view, name='person_add'),
    path('list/', views.UserDetailView.as_view(), name='person_list'),
    path('<int:pk>/', views.person_update_view, name='person_change'),
    path('ajax/load-cities/', views.load_branches, name='ajax_load_branches'),

]

credentials/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
]

banksite_app/models.py
from django.db import models


# Create your models here.
SAVINGS_ACCOUNT = 'Savings Account'
CURRENT_ACCOUNT = 'Current Account'

ACCOUNT_CHOICES = [
    (SAVINGS_ACCOUNT,SAVINGS_ACCOUNT),
    (CURRENT_ACCOUNT,CURRENT_ACCOUNT)
]

class District(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Branch(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Person(models.Model):
    name = models.CharField(max_length=124)
    dob = models.DateField(max_length=100)
    age = models.IntegerField()
    gender = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=100)
    mailid = models.EmailField(max_length=100)
    address = models.TextField(max_length=500)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, blank=True, null=True)
    branch = models.ForeignKey(Branch, on_delete=models.SET_NULL, blank=True, null=True)
    ac_type = models.CharField(max_length=100, choices=ACCOUNT_CHOICES)
    materials = models.CharField(max_length=100)

    def __str__(self):
        return self.name

credentials/models.py
from django.db import models

# Create your models here.

banksite_app/forms.py
from django import forms

from .models import Person, Branch


class PersonCreationForm(forms.ModelForm):
    CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other'),
    ]
    MATERIALS = [
        ('Debit Card', 'Debit Card'),
        ('Credit Card', 'Credit Card'),
        ('Cheque Book', 'Cheque Book'),
        ('Passbook', 'Passbook'),
    ]
    gender = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)
    materials = forms.MultipleChoiceField(required=False, widget=forms.CheckboxSelectMultiple, choices=MATERIALS)

    class Meta:
        model = Person
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['branch'].queryset = Branch.objects.none()

        if 'district' in self.data:
            try:
                district_id = int(self.data.get('district'))
                self.fields['branch'].queryset = Branch.objects.filter(district_id=district_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['branch'].queryset = self.instance.district.branch_set.order_by('name')

banksite_app/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, TemplateView

from .models import Branch, Person
from .forms import PersonCreationForm


# Create your views here.
def Home(request):
    return render(request, 'home.html')


def person_create_view(request):
    form = PersonCreationForm()
    if request.method == 'POST':
        form = PersonCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request,"Your application has been accepted")
            return redirect('person_add')
    return render(request, 'persons.html', {'form': form})

class UserDetailView(View):
    def get(self,request,*args,**kwargs):
        ab=Person.objects.all()
        return render(request,"person_list.html",{'persons':ab})


def person_update_view(request, pk):
    person = get_object_or_404(Person, pk=pk)
    form = PersonCreationForm(instance=person)
    if request.method == 'POST':
        form = PersonCreationForm(request.POST, instance=person)
        if form.is_valid():
            form.save()
            return redirect('person_change', pk=pk)
    return render(request, 'persons.html', {'form': form})


# AJAX
def load_branches(request):
    district_id = request.GET.get('district_id')
    branches = Branch.objects.filter(district_id=district_id).all()
    return render(request, 'branch_dropdown_list_options.html', {'branches': branches})

credentials/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,"Invalid User")
            return redirect('login')
    return render(request, "login.html")


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        cpassword = request.POST['password1']
        if password == cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request, "Username is already taken")
                return redirect('register')
            if User.objects.filter(email=email).exists():
                messages.info(request, "Email-ID is already taken")
                return redirect('register')
            else:
                user = User.objects.create_user(username=username, password=password, email=email)

                user.save();
                return redirect('login')
        else:
            messages.info(request, "password not matched")
            return redirect('register')
        return redirect('/')
    return render(request, "register.html")


def logout(request):
    auth.logout(request)
    return redirect('/')

templates/branch_dropdown_list_options.html
<option value="">---------</option>
{% for branch in branches %}
<option value="{{ branch.pk }}">{{ branch.name }}</option>
{% endfor %}

templates/home.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]><html class="lt-ie9 lt-ie8 lt-ie7"><![endif]-->
<!--[if IE 7]><html class="lt-ie9 lt-ie8"><![endif]-->
<!--[if IE 8]><html class="lt-ie9"><![endif]-->
<!--[if gt IE 8]><!--><html><!--<![endif]-->
<head>
<title>Home Page</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
<link rel="stylesheet" href="{% static 'css/superfish.css' %}">
<link rel="stylesheet" href="{% static 'css/stylesheet.css' %}">
<link rel="stylesheet" href="{% static 'js/slider/flexslider.css' %}">
<link rel="stylesheet" href="{% static 'js/slider/flexcar.css' %}">
<link href='http://fonts.googleapis.com/css?family=Quando' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,300|Droid+Serif:400,300' rel='stylesheet' type='text/css'>
<script src="{% static 'js/vendor/custom.modernizr.js' %}"></script>
<script>
Modernizr.load({
    // test if browser understands media queries
    test: Modernizr.mq('only all'),
    // if not load ie8-grid
    nope: 'css/ie8-grid-foundation-4.css'
});
</script>
<!--[if lt IE 9]>
<link rel="stylesheet" href="{% static 'css/ie-fixes.css' %}">
<![endif]-->
</head>
<body>
<div class="cointainer">
  <div class="header">
    <div class="row">
      <div class="columns large-12  header-inner"> <a href="index.html"><img src="{% static 'images/logo.png' %}" alt="" class="logo"></a> </div>
      <div class="columns large-12">
        <nav>
          <section>
            <ul class="sf-menu large-12">
              <li class="active"><a href="/">Home</a></li>
              <li class="has-dropdown"><a href="services.html">Branches</a>
                <ul class="dropdown">
                  <li class="has-dropdown"><a href="#">Thrissur</a></li>
                  <li><a href="#">Ernakulam</a></li>
                  <li><a href="#">Kottayam</a></li>
                  <li><a href="#">Trivandrum</a></li>
                  <li><a href="#">Calicut</a></li>
                </ul>
              </li>
              {% if user.is_authenticated %}
              <li><a href="credentials/logout">Logout</a></li>
              <li><a href="add/">Application</a></li>
              {% else %}
              <li><a href="credentials/login">Login</a></li>
              <li><a href="credentials/register">Register</a></li>
              {% endif %}
              <li><a href="#">Contact Us</a></li>
            </ul>
          </section>
        </nav>
      </div>
    </div>
    <div class="slider">
      <div class="row">
        <div class="columns large-12">
          <div class="row flexslider-row">
            <div class="columns large-12">
              <div class="flexslider">
                <ul class="slides">
                  <li><img src="{% static 'images/slide1.jpg' %}" alt=""></li>
                  <li><img src="{% static 'images/slide2.jpg' %}" alt=""></li>
                  <li><img src="{% static 'images/slide3.jpg' %}" alt=""></li>
                  <li><img src="{% static 'images/slide4.jpg' %}" alt=""></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="tagline-row">
      <div class="row tagline">
        <div class="columns large-12">
          <h2 class="center">Tincidunt. ac urna urna facilisis etiam platea ac phasellus vut pulvinar dolor porta augue montes odio dapibus elementum augue ultricies quis.</h2>
        </div>
      </div>
    </div>
    <div class="service-box">
      <div class="row service">
        <div class="columns large-4">
          <div class="box">
            <p><img src="{% static 'images/threeup1.jpg' %}" alt="" class="service-img"></p>
            <h1>Lorem ipsum sit dolor esm</h1>
            <p>cum magna diam Duis amagna augue natoque odion nisi sed magna nascetur turpis inet sed parturient cum velit lacus Magna facilisis et cursus montes Turpisinet magnis parturient turpis magna turpis habitasse integ ultricies odion adipiscing eros nisi nunc aliquet lorem ipsum sites dolor esme turpis magna augue odio nisi phasellus pulvinar </p>
          </div>
        </div>
        <div class="columns large-4">
          <div class="box">
            <p><img src="{% static 'images/threeup2.jpg' %}" alt="" class="service-img"></p>
            <h1>Phasell pulvinar magna</h1>
            <p>cum magna diam Duis amagna augue natoque odion nisi sed magna nascetur turpis inet sed parturient cum velit lacus Magna facilisis et cursus montes Turpisinet magnis parturient turpis magna turpis habitasse integ ultricies odion adipiscing eros nisi nunc aliquet lorem ipsum sites dolor esme turpis magna augue odio nisi phasellus pulvinar </p>
          </div>
        </div>
        <div class="columns large-4">
          <div class="box">
            <p><img src="{% static 'images/threeup3.jpg' %}" alt="" class="service-img"></p>
            <h1>Lorem ipsum sit dolor esm</h1>
            <p>cum magna diam Duis amagna augue natoque odion nisi sed magna nascetur turpis inet sed parturient cum velit lacus Magna facilisis et cursus montes Turpisinet magnis parturient turpis magna turpis habitasse integ ultricies odion adipiscing eros nisi nunc aliquet lorem ipsum sites dolor esme turpis magna augue odio nisi phasellus pulvinar </p>
          </div>
        </div>
      </div>
    </div>
    <div class="testimonial-row">
      <div class="row">
        <div class="columns large-11">
          <div class="testimonial flexcar">
            <ul class="slides">
              <li>
                <p>Tincidunt. Ac urna urna facilisis etiam platea ac, phasellus, vut pulvinar? Dolor! Porta augue. Montes odio dapibus Elementum augue ultricies quis ridiculus aliquam vut, dis nunc diam! Arcu aliquet odio in. Eu sed et mauris tincidunt. Ultricies. Massa egestas, odio et arcu egestas egestas integer, urna cras nunc egestas, lorem no Facilisis enim cum nascetur placerat magna magna cursus natoque velit porttitor turpis rcu ac vel natoque enim dictumst urna phasellus tincidunt aliquet Tincidunt urna urna facilisis etiam platea ac, phasellus, vut pulvinar? Dolor! Porta augue. Montes odio dapibus? Elementum augue ultricies quis. Ac ridiculus, aliquam,</p>
              </li>
              <li>
                <p>cum magna diam Duis amagna augue natoque odion nisi sed magna nascetur turpis inet sed parturient cum velit lacus Magna facilisis et cursus montes Turpisinet magnis parturient turpis magna turpis habitasse integ ultricies odion adipiscing eros nisi nunc aliquet lorem ipsum sites dolor esme </p>
              </li>
              <li>
                <p>Massa egestas, odio et arcu egestas egestas integer, urna cras nunc egestas cum magna diam Duis amagna augue natoque odion nisi sed magna nascetur turpis inet sed parturient cum velit lacus Magna facilisis et cursus montes Turpisinet magnis parturient turpis magna turpis habitasse integ ultricies odion adipiscing eros nisi nunc aliquet lorem ipsum sites dolor esme </p>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <footer class="footer">
      <div class="row">
        <div class="columns large-12 footer-inner">
          <div class="row">
            <div class="columns large-3 box">
              <div class="">
                <h2 class="footer-title">Resources</h2>
                <ul>
                  <li><a href="index.html">home</a></li>
                  <li><a href="gallery.html">gallery</a></li>
                  <li><a href="#">faqs</a></li>
                  <li><a href="contact.html">contact us</a></li>
                  <li><a href="#">testimonials</a></li>
                  <li><a href="blog.html">blog</a></li>
                </ul>
              </div>
            </div>
            <div class="columns large-3 box">
              <div>
                <h2 class="footer-title">links </h2>
                <ul>
                  <li><a href="index.html">home</a></li>
                  <li><a href="gallery.html">gallery</a></li>
                  <li><a href="#">faqs</a></li>
                  <li><a href="contact.html">contact us</a></li>
                  <li><a href="#">testimonials</a></li>
                  <li><a href="blog.html">blog</a></li>
                </ul>
              </div>
            </div>
            <div class="columns large-3 box">
              <div>
                <h2 class="footer-title">follow us</h2>
                <ul>
                  <li><a href="#" class="media tweeter"></a>Follow us on twitter</li>
                  <li><a href="#" class="media youtube"></a>Follow us on youtube</li>
                  <li><a href="#" class="media facebook"></a>Follow us on facebook</li>
                  <li><a href="#" class="media gmail"></a>Follow us on google plus</li>
                </ul>
              </div>
            </div>
            <div class="columns large-3 box">
              <div>
                <h2 class="footer-title">Contact us</h2>
                <p>255, Willson Street,Caulfield, 122211, Melbourne</p>
                <p><b>Tel:</b> (122)3456789, (121)3456079, (121)2341234</p>
                <p><b>Fax:</b> (121)5647289, (122)34526589</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <div class="credit-row">
      <div class="row">
        <div class="columns large-11 credit">&copy; 2045 All rights reserved by <a href="#">DreamzBank.</a> Design by: <a href="http://topwebsitetemplates.org">topwebsitetemplates.org</a></div>
        <div class="columns large-1"><img src="{% static 'images/toparrow.png' %}" alt="" class="scrollToTop"></div>
      </div>
    </div>
  </div>
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/superfish.js' %}"></script>
<script src="{% static 'js/slider/jquery.flexslider.js' %}"></script>
<script>
Modernizr.load({
    test: Modernizr.placeholder,
    nope: 'js/placeholder.min.js'
});

function goToNewPage() {
    if (document.getElementById('target').value) {
        window.location.href = document.getElementById('target').value;
    }
}
</script>
<script>
$(document).ready(function () {
    $('ul.sf-menu').superfish({
        animation: {
            height: 'show'
        },
        delay: 400
    });
    $("img.scrollToTop").click(function () {
        $("html, body").animate({
            scrollTop: 0
        }, "slow");
    });
    $('.flexslider').flexslider();
    $('.flexcar').flexslider();
});
</script>
</body>
</html>

templates/persons.html
{% load static %}
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Application</title>
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
<link rel="stylesheet" href="{% static 'css/superfish.css' %}">
<link rel="stylesheet" href="{% static 'css/stylesheet.css' %}">
<link rel="stylesheet" href="{% static 'js/slider/flexslider.css' %}">
<link rel="stylesheet" href="{% static 'js/slider/flexcar.css' %}">
<link href='http://fonts.googleapis.com/css?family=Quando' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,300|Droid+Serif:400,300' rel='stylesheet' type='text/css'>
<script src="{% static 'js/vendor/custom.modernizr.js' %}"></script>
<script>
Modernizr.load({
    // test if browser understands media queries
    test: Modernizr.mq('only all'),
    // if not load ie8-grid
    nope: 'css/ie8-grid-foundation-4.css'
});
</script>
<!--[if lt IE 9]>
<link rel="stylesheet" href="{% static 'css/ie-fixes.css' %}">
<![endif]-->
</head>
<body>
<div class="container">
  <div class="header">
    <div class="row">
      <div class="columns large-12  header-inner"> <a href="index.html"><img src="{% static 'images/logo.png' %}" alt="" class="logo"></a> </div>
		<div class="columns large-12">
        <nav>
          <section>
            <ul class="sf-menu large-12">
              <li class="active"><a href="/">Home</a></li>
              <li class="has-dropdown"><a href="services.html">Branches</a>
                <ul class="dropdown">
                  <li class="has-dropdown"><a href="#">Thrissur</a></li>
                  <li><a href="#">Ernakulam</a></li>
                  <li><a href="#">Kottayam</a></li>
                  <li><a href="#">Trivandrum</a></li>
                  <li><a href="#">Calicut</a></li>
                </ul>
              </li>
            </ul>
          </section>
        </nav>
      </div>
	</div>
  </div>
</div>
</br>
<center><h2><b>Application Form</b></h2></center>

<div class="container mt-3" style="width: 80%; font-size: 14px">
    <form method="post" class="card p-3 mt-5" id="personForm" data-branches-url="{% url 'ajax_load_branches' %}">
        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                {{ form.name|as_crispy_field }}
            </div>
             <div class="col-6">
                {{ form.dob|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.age|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.mailid|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.phone_number|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.ac_type|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.district|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.branch|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.gender|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.materials|as_crispy_field }}
            </div>
            <div>
                {{ form.address|as_crispy_field }}
            </div>
            {% if form.is_save %}
            <div class="col-6" align="right">
                <button type="submit" class="btn btn-primary">Message</button>
            </div>
            <div class="col-6">
                <button class="btn btn-danger" onclick="#">Loging</button>
            </div>
            {% else %}
            <div class="col-6" align="right">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
            <div class="col-6">
                <button class="btn btn-danger" onclick="#">Logout</button>
            </div>
            {% endif %}
        </div>

<!--        {{ form|crispy }}-->

    </form>
</div>
    <footer class="footer">
      <div class="row">
        <div class="columns large-12 footer-inner">
          <div class="row">
            <div class="columns large-3 box">
              <div class="">
                <h2 class="footer-title">Resources</h2>
                <ul>
                  <li><a href="index.html">home</a></li>
                  <li><a href="gallery.html">gallery</a></li>
                  <li><a href="#">faqs</a></li>
                  <li><a href="contact.html">contact us</a></li>
                  <li><a href="#">testimonials</a></li>
                  <li><a href="blog.html">blog</a></li>
                </ul>
              </div>
            </div>
            <div class="columns large-3 box">
              <div>
                <h2 class="footer-title">links </h2>
                <ul>
                  <li><a href="index.html">home</a></li>
                  <li><a href="gallery.html">gallery</a></li>
                  <li><a href="#">faqs</a></li>
                  <li><a href="contact.html">contact us</a></li>
                  <li><a href="#">testimonials</a></li>
                  <li><a href="blog.html">blog</a></li>
                </ul>
              </div>
            </div>
            <div class="columns large-3 box">
              <div>
                <h2 class="footer-title">follow us</h2>
                <ul>
                  <li><a href="#" class="media tweeter"></a>Follow us on twitter</li>
                  <li><a href="#" class="media youtube"></a>Follow us on youtube</li>
                  <li><a href="#" class="media facebook"></a>Follow us on facebook</li>
                  <li><a href="#" class="media gmail"></a>Follow us on google plus</li>
                </ul>
              </div>
            </div>
            <div class="columns large-3 box">
              <div>
                <h2 class="footer-title">Contact us</h2>
                <p>255, Willson Street,Caulfield, 122211, Melbourne</p>
                <p><b>Tel:</b> (122)3456789, (121)3456079, (121)2341234</p>
                <p><b>Fax:</b> (121)5647289, (122)34526589</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <div class="credit-row">
      <div class="row">
        <div class="columns large-11 credit">&copy; 2045 All rights reserved by <a href="#">DreamzBank.</a> Design by: <a href="http://topwebsitetemplates.org">topwebsitetemplates.org</a></div>
        <div class="columns large-1"><img src="{% static 'images/toparrow.png' %}" alt="" class="scrollToTop"></div>
      </div>
    </div>
  </div>
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/superfish.js' %}"></script>
<script src="{% static 'js/slider/jquery.flexslider.js' %}"></script>
<script>
Modernizr.load({
    test: Modernizr.placeholder,
    nope: 'js/placeholder.min.js'
});

function goToNewPage() {
    if (document.getElementById('target').value) {
        window.location.href = document.getElementById('target').value;
    }
}
</script>
<script>
$(document).ready(function () {
    $('ul.sf-menu').superfish({
        animation: {
            height: 'show'
        },
        delay: 400
    });
    $("img.scrollToTop").click(function () {
        $("html, body").animate({
            scrollTop: 0
        }, "slow");
    });
    $('.flexslider').flexslider();
    $('.flexcar').flexslider();
});
</script>


<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>

    $("#id_district").change(function () {
        const url = $("#personForm").attr("data-branches-url");
        const districtId = $(this).val();

        $.ajax({
            url: url,
            data: {
                'district_id': districtId
            },
            success: function (data) {
                $("#id_branch").html(data);



            }
        });

    });
</script>

</body>
</html>